"""empty message

Revision ID: 1e88a79726af
Revises: e8b1651f3ffa
Create Date: 2020-01-29 20:46:35.858885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e88a79726af'
down_revision = 'e8b1651f3ffa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time__zone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('utc', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('time__zone')
    # ### end Alembic commands ###
