"""empty message

Revision ID: 1ffb40fc8409
Revises: 1e88a79726af
Create Date: 2020-01-29 22:24:49.739038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ffb40fc8409'
down_revision = '1e88a79726af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('world_cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_country_subcountry', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('world_cities')
    # ### end Alembic commands ###
