"""empty message

Revision ID: 696008871794
Revises: 1ffb40fc8409
Create Date: 2020-01-29 22:28:16.205421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '696008871794'
down_revision = '1ffb40fc8409'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('world_cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('subcountry', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('world_cities')
    # ### end Alembic commands ###
