"""empty message

Revision ID: a1c075d58da2
Revises: 7eba8b9667d9
Create Date: 2020-12-29 07:47:55.093227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1c075d58da2'
down_revision = '7eba8b9667d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('language',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=100), nullable=False),
    sa.Column('identifier', sa.String(length=100), nullable=False),
    sa.Column('transelator_en_name', sa.String(length=150), nullable=False),
    sa.Column('language', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('language')
    # ### end Alembic commands ###
