"""empty message

Revision ID: c9ad9cc644d5
Revises: 
Create Date: 2020-01-07 04:05:12.066676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9ad9cc644d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quran', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quran', sa.Column('test', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
