"""empty message

Revision ID: d0e5fae72c27
Revises: df93d7ffc427
Create Date: 2020-12-23 18:47:25.825275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0e5fae72c27'
down_revision = 'df93d7ffc427'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('world_cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=300), nullable=False),
    sa.Column('country', sa.String(length=300), nullable=False),
    sa.Column('subcountry', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('world_cities')
    # ### end Alembic commands ###
